chat/urls.py
from django.urls import path
from . import views
app_name = "chat"
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:room_name>/', views.room, name="room"),
    path('user/login/', views.loginUser, name="login"),
    path('user/logout/', views.logoutUser, name="logout"),
    path('user/register/', views.registerUser, name="register"),
    path('user/create-room/', views.createRoom, name="create-room"),
    path('user/join-room/', views.joinRoom, name="join-room"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

chat/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'chat/index.html', {})


@login_required(login_url='chat:login')
def room(request, room_name):

    return render(request, 'chat/chatroom.html', {
        'room_name': room_name,
    })


def logoutUser(request):
    logout(request)
    return redirect('chat:index')


def loginUser(request):
    page = 'login'
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)  # creates session
                return redirect('chat:index')
            else:
                messages.add_message(
                    request,  'Username or password is not correct')
        except:
            messages.add_message(
                request, messages.INFO, 'Username or password is not correct')
    return render(request, 'chat/login_register.html', {'page': page})


@login_required(login_url='chat:login')
def createRoom(request):
    page = "create"
    if request.method == "POST":
        room_name = request.POST['room_name']
        return redirect('chat:room', room_name)
    return render(request, 'chat/create_room.html', {'page': page})


@login_required(login_url='chat:login')
def joinRoom(request):
    page = "join"
    if request.method == "POST":
        room_name = request.POST['room_name']
        return redirect('chat:room', room_name)
    return render(request, 'chat/create_room.html', {'page': page})


def registerUser(request):
    page = "register"
    if request.method == "POST":
        try:
            if User.objects.get(username=request.POST["username"]):
                messages.add_message(
                    request, messages.INFO, 'Username already exist')
        except:
            user = User.objects.create(
                username=request.POST["username"],
                password=request.POST["password"]
            )
            login(request, user)
            return redirect('chat:index')
    return render(request, 'chat/login_register.html', {'page': page})

chat/templates/chat/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

chat/templates/chat/chatroom.html
{% extends 'main.html' %} {% block content %}
<style>
  .box {
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .form-elem {
    width: 100%;
  }
  #submit {
    height: 40px;
    margin-top: 10px;
    border:1px solid black;
    font-weight:bold;
  }
  #submit:hover{
    background-color:#98fb98;
  
  }
  .username {
    color: blue;
  }
 
  #chat-block {
    height: 400px;
    padding-top:5px;
    box-shadow: rgba(0, 0, 0, 0.16) 0px 10px 36px 0px, rgba(0, 0, 0, 0.06) 0px 0px 0px 1px;
  }
  .msg {
    padding: 3px 10px;
  }
</style>
<div class="box">
  <div class="form-container">
    <form>
      <div id="chat-block" class="form-elem"></div>
      <br />
      <input type="text" id="chat-input" class="form-elem" size="80" />
      <br />
      <input id="submit" type="button" class="form-elem" value="Send" />
    </form>
    <div class="form-container"></div>
    <div id="user-block"></div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {{ room_name|json_script:"room_name"}}
    {{request.user.username|json_script:"user-name"}}
    <script>
      let isSubmit = false;
      const roomName = JSON.parse(
        document.getElementById("room_name").textContent
      );
      const username = JSON.parse(
        document.getElementById("user-name").textContent
      );
      const chatSocket = new WebSocket(
        `ws://${window.location.host}/ws/chat/${roomName}/`
      );
      chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        document.getElementById(
          "chat-block"
        ).innerHTML += `<div class="msg" ><span class="username">${data.username}</span>: ${data.message}</div> `;
      };
      function helper(e) {
        e.preventDefault();
        const chatText = document.getElementById("chat-input");
        const message = chatText.value;
        console.log(message);
        chatSocket.send(
          JSON.stringify({
            message: message,
            username: username,
          })
        );
        chatText.value = "";
      }
      function handler(e) {
        if (e.key === "Enter") {
          helper(e);
        }
      }
      function handlerClick(e) {
        helper(e);
      }
      document
        .getElementById("chat-input")
        .addEventListener("keydown", handler);
      document.getElementById("submit").addEventListener("click", handlerClick);
    </script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    {% endblock %}
  </div>
</div>

chat/templates/chat/create_room.html
{% extends 'main.html' %}
{% block content %}
<style>
    .container{
        width:30%;
    }
</style>
<form action="" method="POST">
    {% csrf_token %}
    <div class="container">
  <!-- Content here -->
  {% if page == "create" %}
  <div class="form-group">
    <label for="exampleInputEmail1">Room name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="room_name" aria-describedby="emailHelp" placeholder="Enter Room name">
  </div>
  <button type="submit" class="btn btn-primary">Create</button>
  {% else %}
  <div class="form-group">
    <label for="exampleInputEmail1">Room name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="room_name" aria-describedby="emailHelp" placeholder="Enter Room name">
  </div>
  <button type="submit" class="btn btn-primary">Join</button>
  {% endif %}
</form>
</div>
  
{% endblock %}

chat/templates/chat/index.html
{% extends 'main.html' %} {% block content %}
<style>
  .button-container {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 10px;
  }
</style>

<div class="button-container">
  <a class="btn btn-primary btn-lg" href="{% url 'chat:create-room' %}" role="button">Create Chat Room</a>
  <a class="btn btn-primary btn-lg" href="{% url 'chat:join-room' %}" role="button">Join Chat Room</a>
</div>
{% endblock %}

chat/templates/chat/login_register.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Simple Login Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style>
	.login-form{
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
{% if page == 'login' %}
<div class="login-form">
    <form action="" method="POST">
        {% csrf_token %}
        <h2 class="text-center">Log in</h2>       
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name = "username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name = "password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="{% url 'chat:register' %}">Create an Account</a></p>
   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
{% else %}
<div class="login-form">
    <form action="" method="POST">
        {% csrf_token %}
        <h2 class="text-center">Register</h2>       
        <div class="form-group">
            <input type="username" class="form-control" placeholder="Username" name="username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
        </div>   
    </form>
    <p class="text-center">
        Already Registered ?<a href="{% url 'chat:login' %}">Log in </a></p>
     {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
{% endif %}

</body>
</html>                                		

templates/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>get Ratings</title>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Varela+Round"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <style>
      body {
        font-family: "Varela Round", sans-serif;
      }
      .form-control {
        box-shadow: none;
        font-weight: normal;
        font-size: 13px;
      }
      .form-control:focus {
        border-color: #33cabb;
        box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
      }

      .navbar {
        background: #fff;
        padding-left: 16px;
        padding-right: 16px;
        border-bottom: 1px solid #dfe3e8;
        border-radius: 0;
      }
      .nav img {
        border-radius: 50%;
        width: 36px;
        height: 36px;
        margin: -8px 0;
        float: left;
        margin-right: 10px;
      }
      .navbar .navbar-brand,
      .navbar .navbar-brand:hover,
      .navbar .navbar-brand:focus {
        padding-left: 0;
        font-size: 20px;
        padding-right: 50px;
      }
      .navbar .navbar-brand b {
        font-weight: bold;
        color: #33cabb;
      }
      .navbar .form-inline {
        display: inline-block;
      }
      .navbar .nav li {
        position: relative;
      }
      .navbar .nav li a {
        color: #888;
      }
      .search-box {
        position: relative;
      }
      .search-box input {
        padding-right: 35px;
        border-color: #dfe3e8;
        border-radius: 4px !important;
        box-shadow: none;
      }
      .search-box .input-group-addon {
        min-width: 35px;
        border: none;
        background: transparent;
        position: absolute;
        right: 0;
        z-index: 9;
        padding: 7px;
        height: 100%;
      }
      .search-box i {
        color: #a0a5b1;
        font-size: 19px;
      }
      .navbar .nav .btn-primary,
      .navbar .nav .btn-primary:active {
        color: #fff;
        background: #33cabb;
        padding-top: 8px;
        padding-bottom: 6px;
        vertical-align: middle;
        border: none;
      }
      .navbar .nav .btn-primary:hover,
      .navbar .nav .btn-primary:focus {
        color: #fff;
        outline: none;
        background: #31bfb1;
      }
      .navbar .navbar-right li:first-child a {
        padding-right: 30px;
      }
      .navbar ul li i {
        font-size: 18px;
      }
      .navbar .dropdown-menu i {
        font-size: 16px;
        min-width: 22px;
      }
      .navbar ul.nav li.active a,
      .navbar ul.nav li.open > a {
        background: transparent !important;
      }
      .navbar .nav .get-started-btn {
        min-width: 120px;
        margin-top: 8px;
        margin-bottom: 8px;
      }
      .navbar ul.nav li.open > a.get-started-btn {
        color: #fff;
        background: #31bfb1 !important;
      }
      .navbar .dropdown-menu {
        border-radius: 1px;
        border-color: #e5e5e5;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
      }
      .navbar .nav .dropdown-menu li {
        color: #999;
        font-weight: normal;
      }
      .navbar .nav .dropdown-menu li a,
      .navbar .nav .dropdown-menu li a:hover,
      .navbar .nav .dropdown-menu li a:focus {
        padding: 8px 20px;
        line-height: normal;
      }
      .navbar .navbar-form {
        border: none;
      }
      .navbar .dropdown-menu.form-wrapper {
        width: 280px;
        padding: 20px;
        left: auto;
        right: 0;
        font-size: 14px;
      }
      .navbar .dropdown-menu.form-wrapper a {
        color: #33cabb;
        padding: 0 !important;
      }
      .navbar .dropdown-menu.form-wrapper a:hover {
        text-decoration: underline;
      }
      .navbar .form-wrapper .hint-text {
        text-align: center;
        margin-bottom: 15px;
        font-size: 13px;
      }
      .navbar .form-wrapper .social-btn .btn,
      .navbar .form-wrapper .social-btn .btn:hover {
        color: #fff;
        margin: 0;
        padding: 0 !important;
        font-size: 13px;
        border: none;
        transition: all 0.4s;
        text-align: center;
        line-height: 34px;
        width: 47%;
        text-decoration: none;
      }
      .navbar .social-btn .btn-primary {
        background: #507cc0;
      }
      .navbar .social-btn .btn-primary:hover {
        background: #4676bd;
      }
      .navbar .social-btn .btn-info {
        background: #64ccf1;
      }
      .navbar .social-btn .btn-info:hover {
        background: #4ec7ef;
      }
      .navbar .social-btn .btn i {
        margin-right: 5px;
        font-size: 16px;
        position: relative;
        top: 2px;
      }
      .navbar .form-wrapper .form-footer {
        text-align: center;
        padding-top: 10px;
        font-size: 13px;
      }
      .navbar .form-wrapper .form-footer a:hover {
        text-decoration: underline;
      }
      .navbar .form-wrapper .checkbox-inline input {
        margin-top: 3px;
      }
      .or-seperator {
        margin-top: 32px;
        text-align: center;
        border-top: 1px solid #e0e0e0;
      }
      .countWl span {
        margin-right: 5px;
      }
      .or-seperator b {
        color: #666;
        padding: 0 8px;
        width: 30px;
        height: 30px;
        font-size: 13px;
        text-align: center;
        line-height: 26px;
        background: #fff;
        display: inline-block;
        border: 1px solid #e0e0e0;
        border-radius: 50%;
        position: relative;
        top: -15px;
        z-index: 1;
      }
      .navbar .checkbox-inline {
        font-size: 13px;
      }
      .navbar .navbar-right .dropdown-toggle::after {
        display: none;
      }
      @media (min-width: 1200px) {
        .form-inline .input-group {
          width: 300px;
          margin-left: 30px;
        }
      }
      @media (max-width: 768px) {
        .navbar .dropdown-menu.form-wrapper {
          width: 100%;
          padding: 10px 15px;
          background: transparent;
          border: none;
        }
        .navbar .form-inline {
          display: block;
        }
        .navbar .input-group {
          width: 100%;
        }
        .navbar .nav .btn-primary,
        .navbar .nav .btn-primary:active {
          display: block;
        }
      }
    </style>
    <script>
      // Prevent dropdown menu from closing when click inside the form
      $(document).on("click", ".navbar-right .dropdown-menu", function (e) {
        e.stopPropagation();
      });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-expand-lg navbar-light">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'chat:index' %}"
          >Lets<b>Chat</b></a
        >
        <button
          type="button"
          data-target="#navbarCollapse"
          data-toggle="collapse"
          class="navbar-toggle"
        >
          <span class="navbar-toggler-icon"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collection of nav links, forms, and other content for toggling -->

      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'chat:logout' %}">Log Out</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'chat:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>